<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <NoWarn>$(NoWarn);NU1903;NU1510</NoWarn>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SanaaOffersApi.Application\SanaaOffersApi.Application.csproj" />
    <ProjectReference Include="..\SanaaOffersApi.Infrastructure\SanaaOffersApi.Infrastructure.csproj" />
  </ItemGroup>

</Project>
